disabled_rules:
  - colon
  - object_literal
  - file_length
  - file_header
  - identifier_name
  - force_cast
  - force_try
  # Remove them after
  - todo
  - cyclomatic_complexity
  - mark
  - multiple_closures_with_trailing_closure
  - weak_delegate
  - function_parameter_count
  - large_tuple
  - class_delegate_protocol
  - nesting
  - valid_ibinspectable
  - discarded_notification_center_observer
opt_in_rules:
  - anyobject_protocol
   - array_init
   - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
   - contains_over_first_not_nil
  - contains_over_range_nil_comparison
   - discouraged_object_literal
  - empty_count
   - explicit_init
   - extension_access_modifier
  - fatal_error_message
   - file_header
   - file_name
  - first_where
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_function_chains
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - legacy_multiple
  - implicit-getter
  - implicit-return
excluded:
  - .bundle
  - Carthage
  - fastlane
  - firebase
  - Pods
  - vendor
  - "*Tests"

line_length:
  warning: 150
  error: 2000
  ignores_comments: true
type_body_length:
  - 300 # warning
  - 400 # error
type_name:
  min_length: 1
  max_length: 75
function_body_length:
  warning: 400
  error: 500
file_length:
  warning: 500
  error: 1200

# SwiftLint
# https://github.com/realm/SwiftLint
# JP - doc
# https://qiita.com/kagemiku/items/80e6d905dc0059c342b3
