#!/bin/sh

if [ "$1" = "" ]; then
    echo "Error \$1: VERSION argv is required!" 1>&2
    exit 1
fi

cd $(dirname $0)/../../..

PROJECT_YML_NAME=project.yml

BUNDLE_BUILD_VERSION_KEY="BUNDLE_BUILD_VERSION: "
BUNDLE_VERSION_KEY="BUNDLE_VERSION: "

VERSION=$1
NEW_BUNDLE_BUILD_VERSION="$BUNDLE_BUILD_VERSION_KEY$VERSION.0"
NEW_BUNDLE_VERSION="$BUNDLE_VERSION_KEY$VERSION"

sed -i "" \
	-e "s/$BUNDLE_BUILD_VERSION_KEY.*/$NEW_BUNDLE_BUILD_VERSION/" \
	-e "s/$BUNDLE_VERSION_KEY.*/$NEW_BUNDLE_VERSION/" \
	$PROJECT_YML_NAME
